### ISSUE TITLE
Github Link to Dictionary App is broken

### ISSUE THREAD

**Issue by zenful-dev** [hellodeborahuk/React-portfolio#1]
Hi Debbie. Your portfolio looks great!

In ProjectList.js file the GitHub link to Dictionary App is broken
https://github.com/hellodeborahuk/dictionary

I think the link should be this-
https://github.com/hellodeborahuk/dictionary-project

**Comment by hellodeborahuk** [comment]
Hi Roshni, the live site sits over on a fork here: https://github.com/danndigital/debbie-portfolio. Can you resubmit the issue over there please, if you'd like to. Thanks for picking up on the wrong link!

**Comment by zenful-dev** [comment]
Okay @hellodeborahuk I will resubmit the issue. Thank you for letting me know the right repo.
